# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0003_auto_20171031_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrica', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data Cadastro')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='uploads/comentario/img/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Usuario')),
            ],
            options={
                'verbose_name': 'Coment\xe1rio',
                'verbose_name_plural': 'Coment\xe1rios',
            },
        ),
    ]
