# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_comentario_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='descrica',
            new_name='descricao',
        ),
    ]
