# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Unidade')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Curso'),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=set([('nome', 'unidade')]),
        ),
    ]
