# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_auto_20171026_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=20),
        ),
    ]
