# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0012_auto_20171209_0033'),
        ('rh', '0004_usuario_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servico.Servico'),
        ),
    ]
