# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_unidade_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servico_usuario', to='servico.Servico'),
        ),
    ]
