# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0013_servico_slug'),
        ('rh', '0006_auto_20171209_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='servico',
        ),
        migrations.AddField(
            model_name='usuario',
            name='servico',
            field=models.ManyToManyField(blank=True, null=True, related_name='servico_usuario', to='servico.Servico'),
        ),
    ]
