# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_auto_20171212_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='servico',
            field=models.ManyToManyField(blank=True, related_name='servico_usuario', to='servico.Servico'),
        ),
    ]
