# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_auto_20171212_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='thumbnail',
        ),
    ]
