# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('servico', '0011_auto_20171128_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='documents/')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('codigo', models.CharField(blank=True, max_length=200, null=True, verbose_name='C\xf3digo')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.Servico')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.Tags')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='anexos',
            unique_together=set([('tag', 'codigo')]),
        ),
    ]
