# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0006_comentario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='documents/')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.Servico')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
    ]
