# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0011_auto_20171128_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='unidade',
        ),
        migrations.AlterField(
            model_name='servico',
            name='criado_por',
            field=models.CharField(max_length=200, verbose_name='Criado por'),
        ),
    ]
