# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_auto_20180128_2325'),
        ('servico', '0015_auto_20180111_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='usuario',
            field=models.ManyToManyField(blank=True, related_name='servico_usuario', to='rh.Usuario'),
        ),
    ]
