# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_auto_20180128_2325'),
        ('servico', '0016_servico_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Unidade'),
        ),
    ]
