# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0017_servico_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servico_unidade', to='rh.Unidade'),
        ),
    ]
