# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0018_auto_20180128_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Servi\xe7o'),
        ),
    ]
