# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_usuario', to='rh.Usuario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_servico', to='servico.Servico'),
        ),
    ]
