# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('post', '0003_remove_post_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='post_tags', to='tag.Tags'),
        ),
    ]
