# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_auto_20180208_0109'),
        ('post', '0004_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='galeria',
        ),
        migrations.AddField(
            model_name='post',
            name='galeria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.Galeria'),
        ),
    ]
