# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_auto_20171031_1647'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrica', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Cadastro')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='uploads/comentario/img/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Usuario')),
            ],
            options={
                'verbose_name': 'Coment\xe1rio',
                'verbose_name_plural': 'Coment\xe1rios',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data Cadastro')),
                ('comentario', models.ManyToManyField(blank=True, to='servico.Comentario')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Usuario')),
                ('galeria', models.ManyToManyField(blank=True, to='servico.Imagens')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome do Servi\xe7o')),
                ('resumo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='uploads/servico/img/')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Usuario')),
                ('post', models.ManyToManyField(blank=True, to='servico.Post')),
                ('unidade', models.ManyToManyField(blank=True, related_name='unidades', to='rh.Unidade', verbose_name='Unidades')),
            ],
            options={
                'verbose_name': 'Servi\xe7o',
                'verbose_name_plural': 'Servi\xe7os',
            },
        ),
    ]
