# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_comentario_post_servico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='data_cadastro',
        ),
    ]
