# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_auto_20171031_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servico.Servico'),
            preserve_default=False,
        ),
    ]
