# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_auto_20171031_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='data',
        ),
        migrations.AddField(
            model_name='comentario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data Cadastro'),
            preserve_default=False,
        ),
    ]
