# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_auto_20171031_1647'),
        ('servico', '0005_auto_20171031_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rh.Usuario'),
            preserve_default=False,
        ),
    ]
