# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0013_servico_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
