# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('servico', '0014_servico_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='has_anexo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servico',
            name='has_carrosel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servico',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='servico_tags', to='tag.Tags'),
        ),
    ]
