# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endere\xe7o')),
                ('cidade', models.CharField(blank=True, max_length=80)),
                ('pais', models.CharField(blank=True, max_length=80, verbose_name='pa\xeds')),
                ('estado', models.CharField(blank=True, max_length=80)),
                ('bairro', models.CharField(blank=True, max_length=80)),
                ('rua', models.CharField(blank=True, max_length=80)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=25)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='uploads/unidade/img/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/unidade/img/thumbnail')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('celular', models.TextField(max_length=20)),
                ('imagem', models.ImageField(blank=True, default='uploads/usuario/img/perfil.png', null=True, upload_to='uploads/usuario/img/')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rh.Usuario')),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admin',
            },
            bases=('rh.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rh.Usuario')),
                ('matricula', models.TextField(max_length=20)),
                ('curso', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Aluno',
            },
            bases=('rh.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.Unidade'),
        ),
    ]
