# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_auto_20180128_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidade',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='servico',
        ),
    ]
