# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anexo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anexos',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='anexos',
            name='tag',
        ),
    ]
